'use client'
import type { Metadata } from "next";
//import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import { usePathname } from "next/navigation";

//const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "CornMarster",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const pathname = usePathname()

  const isDashboard = pathname.startsWith('/dashboard')
  return (
    <html lang="en">

      <body>
      {!isDashboard && (
        <Header bgColor="bg-white"/>
      )}

        <main>{children}</main>

        {!isDashboard && (
        <Footer/>
      )}

      </body>

    </html>
  );
}
