'use client'
import type { Metadata } from "next";
//import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import { usePathname } from "next/navigation";
import { useEffect, useState } from "react";
import Head from "next/head";
import { AuthProvider } from "@/context/AuthContext";

import NProgress from 'nprogress'
import "nprogress/nprogress.css"
//const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "CornMarster",
//   description: "Generated by create next app",
// };

NProgress.configure({ showSpinner: false })

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const pathname = usePathname()

  // const pathname = usePathname()

  useEffect(() => {
    NProgress.start()
    const timer = setTimeout(() => {
      NProgress.done()
    }, 500) // Simule un chargement court si la page est déjà prête

    return () => {
      clearTimeout(timer)
      NProgress.done()
    }
  }, [pathname])

  const isDashboard = pathname.startsWith('/dashboard')
  return (
    <html lang="en">


      <body>
      <div id="__next">
      {!isDashboard && (
        <Header bgColor="bg-white"/>
      )}

      <AuthProvider>
            <main>
              {children}
            </main>
      </AuthProvider>
        {!isDashboard && (
        <Footer/>
      )}
      </div>
      </body>

    </html>
  );
}
